---
- name: Remove existing app directory
  file:
    path: /opt/nodejs-service-deployment
    state: absent
  become: true

- name: Clone Node.js service repo
  git:
    repo: "https://github.com/WilliamFly/nodejs-service-deployment.git"
    dest: /opt/nodejs-service-deployment
    version: main
  become: true

- name: Install npm dependencies
  npm:
    path: /opt/nodejs-service-deployment
    production: true
  become: true

- name: Deploy systemd service file
  template:
    src: nodeapp.service.j2
    dest: /etc/systemd/system/nodeapp.service
  become: true

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  become: true

- name: Enable and restart nodeapp service
  systemd:
    name: nodeapp
    enabled: true
    state: restarted
  become: true
