---
- name: Configure DevOps Server
  hosts: devops_server
  become: true

  roles:
    - role: base
      tags: base
    - role: nginx
      tags: nginx
    - role: ssh
      tags: ssh
    - role: app
      tags: app
      when: deploy_method == "tarball"
    - role: github-app
      tags: github-app
      when: deploy_method == "git"
